services:
  training-datasets-management: 
    image: mongo
    container_name: training-datasets-management-container
    volumes:
      - ./data/db:/data/db
    ports:
      - 27000:27017
    networks:
      - training-datasets-management-network

  training-datasets-management-webapp: 
    build: .
    container_name: training-datasets-management-webapp-container
    command: npm run dev
    ports:
      - 4000:3000
    volumes:
      - ./src:/training-data-management-webapp/src:ro
      - ./next.config.mjs:/training-data-management-webapp/next.config.mjs:ro
    environment:
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    networks:
      - training-datasets-management-network

networks:
  training-datasets-management-network: 
    driver: bridge