import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/utils/tw-cn";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import Header from "@/components/header/Header";
import { PropsWithChildren } from "react";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col gap-2 container px-2",
          fontSans.variable
        )}
      >
        <ReactQueryProvider>
          <TooltipProvider>
            <Header />
            <main className="flex h-full flex-1">
              {children}
            </main>
          </TooltipProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
